### ISSUE TITLE
libtorrent module not found

### ISSUE THREAD

**Issue by sleeping4cat** [iw4p/torrentp#8]
I am receiving this module not found error

```Python
Traceback (most recent call last):
  File "f:/CS/Alpha Tauri/OX-base/torrent+download.py", line 3, in <module>
    from torrentp import TorrentDownloader
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\torrentp\__init__.py", line 6, in <module>
    from .torrent_downloader import TorrentDownloader
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\torrentp\torrent_downloader.py", line 4, in <module>
    import libtorrent as lt
ImportError: DLL load failed while importing libtorrent: The specified module could not be found.
```

**Comment by iw4p** [comment]
Hi, please use Google Colab. Also, May I know your Python version number? Because It has some bugs with newer versions of python and I think it is fine with 3.9 or older versions of Python.

**Comment by sleepingcat4** [comment]
I am using Python 3.8.10 

But I want to use it on my windows as I am developing an application based on this library. Can you provide any help?

**Comment by aoout** [comment]
@sleepingcat4 
I found that this problem does not occur on 3.8.1.

**Comment by sleepingcat4** [comment]
@aoout thank you for the update!
